# Generated by Django 5.2.1 on 2025-06-28 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_profile_picture_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
